[package]
name = "workflow-verifier-product"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
toml.workspace = true
workflow-verifier-domain = { path = "../domain", version = "=0.1.0" }
workflow-verifier-foundation = { path = "../foundation", version = "=0.1.0" }
workflow-verifier-frontend = { path = "../frontend", version = "=0.1.0" }
workflow-verifier-syntax = { path = "../syntax", version = "=0.1.0" }
workflow-verifier-verifier = { path = "../verifier", version = "=0.1.0" }

[lints]
workspace = true
