[package]
name = "workflow-verifier-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
workflow-verifier-domain = { path = "../domain" }
workflow-verifier-foundation = { path = "../foundation" }
workflow-verifier-syntax = { path = "../syntax" }

[lints]
workspace = true
