[package]
name = "workflow-verifier-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
workflow-verifier-domain = { path = "../domain" }
workflow-verifier-foundation = { path = "../foundation" }
workflow-verifier-frontend = { path = "../frontend" }
workflow-verifier-runner-protocol = { path = "../../helpers/protocol" }
workflow-verifier-verifier = { path = "../verifier" }

[lints]
workspace = true
