#!/usr/bin/env python3
"""Fail if the analyzer acquires foreign stubs, bindings, or subprocess linters."""

from __future__ import annotations

import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
ANALYZER_ROOTS = [ROOT / "lib", ROOT / "bin"]
FORBIDDEN_SUFFIXES = {".c", ".cc", ".cpp", ".h", ".dll", ".so", ".dylib"}
FORBIDDEN_DUNE = ("foreign_stubs", "foreign_archives", "ctypes", "unix")
# odoc is generated by Dune behind with-doc; it never enters the analyzer link.
ALLOWED_OPAM_DEPENDENCIES = {"ocaml", "dune", "odoc"}


def fail(message: str) -> None:
    print(f"pure-OCaml gate: {message}", file=sys.stderr)
    raise SystemExit(1)


def opam_dependency_names(source: str) -> set[str]:
    """Read top-level strings in the depends list, excluding filter literals."""
    match = re.search(r"(?m)^depends\s*:\s*\[", source)
    if match is None:
        raise ValueError("opam depends stanza is missing")

    names: set[str] = set()
    square_depth = 1
    brace_depth = 0
    index = match.end()
    while index < len(source) and square_depth:
        character = source[index]
        if character == '"':
            index += 1
            value: list[str] = []
            while index < len(source) and source[index] != '"':
                if source[index] == "\\" and index + 1 < len(source):
                    index += 1
                value.append(source[index])
                index += 1
            if index >= len(source):
                raise ValueError("unterminated string in opam depends stanza")
            if square_depth == 1 and brace_depth == 0:
                names.add("".join(value))
        elif character == "[":
            square_depth += 1
        elif character == "]":
            square_depth -= 1
        elif character == "{":
            brace_depth += 1
        elif character == "}":
            brace_depth -= 1
            if brace_depth < 0:
                raise ValueError("unbalanced filter in opam depends stanza")
        index += 1

    if square_depth != 0 or brace_depth != 0:
        raise ValueError("unterminated opam depends stanza")
    return names


def run() -> None:
    for root in ANALYZER_ROOTS:
        for path in sorted(root.rglob("*")):
            if path.is_file() and path.suffix.lower() in FORBIDDEN_SUFFIXES:
                fail(f"foreign source or binary under analyzer: {path.relative_to(ROOT)}")
            if path.name == "dune":
                source = path.read_text(encoding="utf-8")
                for marker in FORBIDDEN_DUNE:
                    if re.search(rf"\b{re.escape(marker)}\b", source, re.IGNORECASE):
                        fail(f"{marker!r} in {path.relative_to(ROOT)}")

    for path in sorted((ROOT / "lib").rglob("*.ml*")):
        source = path.read_text(encoding="utf-8")
        for marker in ("Unix.", "Ctypes.", "Yaml."):
            if marker in source:
                fail(f"foreign/process boundary {marker!r} in {path.relative_to(ROOT)}")

    opam = (ROOT / "workflow-verifier.opam").read_text(encoding="utf-8")
    try:
        dependencies = opam_dependency_names(opam)
    except ValueError as error:
        fail(str(error))
    unexpected = dependencies - ALLOWED_OPAM_DEPENDENCIES
    if unexpected:
        fail(f"unexpected analyzer dependencies: {', '.join(sorted(unexpected))}")

    print("pure-OCaml gate: stdlib-only analyzer, no foreign stubs, no subprocess linter")


if __name__ == "__main__":
    run()
