(install
 (package workflow-verifier)
 (section share)
 (files
  (workflow-verifier.bash as completions/workflow-verifier.bash)
  (_workflow-verifier as completions/_workflow-verifier)
  (workflow-verifier.fish as completions/workflow-verifier.fish)
  (workflow-verifier.ps1 as completions/workflow-verifier.ps1)))
