[package]
name = "workflow-verifier-macos-helper"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "workflow-verifier-macos-helper"
path = "src/main.rs"

[dependencies]
workflow-verifier-helper-runtime = { path = "../runtime", version = "=0.1.0" }
workflow-verifier-runner-protocol = { path = "../protocol", version = "=0.1.0" }

[lints]
workspace = true
