[package]
name = "workflow-verifier-macos-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "workflow-verifier-macos-helper"
path = "src/main.rs"

[dependencies]
workflow-verifier-internal = { package = "workflow-verifier", path = "../..", version = "=0.1.0", default-features = false, features = ["internal-support"] }

[lints]
workspace = true
